# Generated by Django 5.2.15 on 2026-07-09 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_alter_employee_options_employee_user_and_more'),
        ('offices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('jam_masuk', models.TimeField(blank=True, null=True)),
                ('jam_pulang', models.TimeField(blank=True, null=True)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('jarak', models.FloatField()),
                ('selfie', models.ImageField(upload_to='attendance/')),
                ('status', models.CharField(choices=[('hadir', 'Hadir'), ('terlambat', 'Terlambat'), ('izin', 'Izin'), ('sakit', 'Sakit'), ('alpa', 'Alpa')], max_length=20)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offices.office')),
            ],
            options={
                'db_table': 'attendance',
            },
        ),
    ]
