# Generated by Django 5.2.15 on 2026-07-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='face_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='attendance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('hadir', 'Hadir'), ('terlambat', 'Terlambat'), ('izin', 'Izin'), ('sakit', 'Sakit'), ('cuti', 'Cuti'), ('alpa', 'Alpa')], max_length=20),
        ),
    ]
