# Generated by Django 5.2.15 on 2026-07-09 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_options_employee_user_and_more'),
        ('offices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='office',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='offices.office'),
            preserve_default=False,
        ),
    ]
