# Generated by Django 5.2.15 on 2026-07-09 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_alter_employee_options_employee_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='faces/')),
                ('encoding', models.TextField()),
                ('model', models.CharField(default='Facenet512', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faces', to='employees.employee')),
            ],
            options={
                'db_table': 'face_data',
            },
        ),
    ]
