# Generated by Django 5.2.15 on 2026-07-09 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_office'),
        ('recognition', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facedata',
            old_name='foto',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='facedata',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='facedata',
            name='model',
        ),
        migrations.AddField(
            model_name='facedata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='facedata',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='facedata',
            name='encoding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
