# Generated by Django 5.2.15 on 2026-07-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0002_rename_foto_facedata_image_remove_facedata_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facedata',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterModelTable(
            name='facedata',
            table=None,
        ),
    ]
